In [1]:
import pandas as pd
from sqlalchemy import create_engine

train = pd.read_csv("../data/raw/train.csv", dtype={"StateHoliday": str})
store = pd.read_csv("../data/raw/store.csv")

engine = create_engine("sqlite:///../data/rossmann.db")

train.to_sql("sales", engine, if_exists="replace", index=False)
store.to_sql("stores", engine, if_exists="replace", index=False)

print("Done")

Done

In [2]:
pd.read_sql("SELECT * FROM sales LIMIT 5", engine)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [3]:
pd.read_sql("SELECT * FROM stores LIMIT 5", engine)

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [4]:
pd.read_sql("SELECT COUNT(*) FROM sales", engine)

   COUNT(*)
0   1017209